### 1 테넌트의 로케이션 조회
GET http://localhost:8080/locations
TENANT_ID: 1
Accept: application/json

### 1 테넌트에게 로케이션 추가
POST http://localhost:8080/locations/someName
TENANT_ID: 1

### 2 테넌트의 로케이션 조회
GET http://localhost:8080/locations
TENANT_ID: 2
Accept: application/json

### 2 테넌트에게 로케이션 추가
POST http://localhost:8080/locations/someName
TENANT_ID: 2
